const StorageParams = {
  CACHED_ADMINS: "CACHED_ADMINS",
  CACHED_USERS: "CACHED_USERS",
  CACHED_PRODUCTS: "CACHED_PRODUCTS",
  CACHED_CATEGORIES: "CACHED_CATEGORIES",
  CACHED_ORDERS: "CACHED_ORDERS",
};

export default StorageParams;
